### ISSUE TITLE
Plugin 404 (index.js)

### ISSUE THREAD

**Issue by go4cas** [jdanyow/aurelia-converters-sample#10]
Hi. First off, awesome docs!

I got everything working, except the final bit - to create the format classes as a plugin.

I've added the following to my `main.js`:

``` javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('./resources/index'); // install our app's resources

  aurelia.start().then(a => a.setRoot());
}
```

I've cerate the `resources` folder, and added the class js files and the `index.js` to this folder.
I've also checked that `aurelia-app="main"` was added to `index.html`.

When the application starts, I get the following error:
**GET http://127.0.0.1:9000/resources/index.js 404 (Not Found)**

Using the classes outside of the plugin, i.e. as `<require>`, it works 100%

**Comment by jdanyow** [comment]
apologies, this is a little out of date, the code should be:

``` js
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .feature('resources'); // install our app's resources

  aurelia.start().then(a => a.setRoot());
}
```

The examples in this repo are moving over to the official docs at http://aurelia.io/docs.html soon.

**Comment by jdanyow** [comment]
Official docs for the `feature` method:  http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.7/doc/article/app-configuration-and-startup

**Comment by go4cas** [comment]
I have tried both your code changes suggested here, as well as per the documentation, but now I keep getting the following exception: "**Unhandled promise rejection TypeError: aurelia.globalizeResources is not a function(...)**"

**Comment by go4cas** [comment]
Thanks! This is fixed now.

For completeness sake, here's my final code snippets:

Under the src directory, I have created the following:

```
src
└ format-lib
     └ currency-format.js
     └ date-format.js
     └ index.js
```

**`date-format.js`**:

``` javascript
export class DateFormatValueConverter {
  toView(value, format) {
    // date formatting logic
    return formattedDate;
  }
}
```

**`index.js`**:

``` javascript
export function configure(config) {
  config.globalResources('./date-format', './currency-format');
}
```

Then, adding the new feature into **`main.js`**:

``` javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-mdl')
    .feature('format-lib');
  aurelia.start().then(a => a.setRoot());
}
```

And finally, this is how I use it:

``` html
<td>${data.OrderDate | dateFormat:'d MMM yyyy @ HH:mm'}</td>
```

**Comment by jdanyow** [comment]
:+1: :rocket:
