### ISSUE TITLE
Change 'import' to 'require'

### ISSUE THREAD

**Issue by Dris101** [jdanyow/aurelia-converters-sample#4]
Great examples and framework feature. Could you update from the old 'import' to the new 'require' in for example:-

``` html
<template>
  <import from="./date-format"></import>
  <import from="./currency-format"></import>

  ${currentDate | dateFormat} <br/>
  ${netWorth | currencyFormat}
</template>
```

I think it is only working at present because you have registered them globally.

**Comment by jdanyow** [comment]
good call- I'll get this repo updated with the latest version of Aurelia.  It's several versions behind.

**Comment by jdanyow** [comment]
done.
