### ISSUE TITLE
Registering Global Plugin example has incorrectly named export function

### ISSUE THREAD

**Issue by MikeJoyce19** [jdanyow/aurelia-converters-sample#5]
In section http://jdanyow.github.io/aurelia-converters-sample/#globally-accessible-value-converters, exported function is install, should be configure

```
export function install(aurelia) {
  aurelia.globalizeResources('./date-format', './number-format');
}
```

should be 

```
export function configure(aurelia) {
  aurelia.globalizeResources('./date-format', './number-format');
}
```

As specified in docs - http://aurelia.io/docs.html#plugins

**Comment by jdanyow** [comment]
thanks @MikeJoyce19
