### ISSUE TITLE
Sample will not run

### ISSUE THREAD

**Issue by csrow** [jdanyow/aurelia-converters-sample#6]
In Chrome, running into problem with Markdown in ES6-loader

"Potentially unhandled rejection [1] Error: Error instantiating Markdown."

**Comment by jdanyow** [comment]
Won't run locally or is the gh-pages site not working for you?

**Comment by csrow** [comment]
Running into problem trying to run it locally.

**Comment by jdanyow** [comment]
ok- I'll update it to the latest aurelia version
