### ISSUE TITLE
Question - Best way to bundle converters

### ISSUE THREAD

**Issue by Martin-Andersen** [jdanyow/aurelia-converters-sample#7]
Hi Thanks for a very nice demo, helped me a lot.

I wonder what's the best way to bundle value converters? And do I need to bundle them? I am afraid of polluting the global namespace.

**Comment by jdanyow** [comment]
Are you referring to the very last example ("Globally Accessible Value Converters") where `globalizeResources` is covered?

If so- not to worry- `globalizeResources` will not pollute the javascript global namespace- it only makes the resources global within the Aurelia application.
